[tool.poetry]
authors = ["m09 <142691+m09@users.noreply.github.com>"]
description = "Tool to handle invoices."
homepage = "https://github.com/m09/invoicez"
license = "Apache-2.0"
name = "invoicez"
readme = "README.md"
version = "4.0.0"

[tool.poetry.dependencies]
GitPython = "^3.1.24"
Jinja2 = "^3.0.2"
PyYAML = "^6.0"
google-api-python-client = "^2.26.1"
google-auth-oauthlib = "^0.4.6"
pydantic = "^1.8.2"
python = "^3.8"
rich = "^10.12.0"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
flake8 = "^4.0.1"
flake8-bugbear = "^21.9.2"
flake8-docstrings = "^1.6.0"
isort = "^5.9.3"
mypy = "^0.910"
"pdfminer.six" = "^20200402"
pylint = "^2.11.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
types-PyYAML = "^5.4.12"

[tool.poetry.scripts]
invoicez = 'invoicez.cli:main'

[tool.isort]
profile = "black"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
