name: CD

on:
  push:
    tags:
      - "*"

jobs:
  deploy-pypi:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build wheel and deploy on PyPI
        run: |
          export TAG=${GITHUB_REF##*/}
          test $(poetry version | cut -f 2 -d " ") = $TAG
          poetry --build publish -u "${{ secrets.PYPI_LOGIN }}" -p "${{ secrets.PYPI_PASSWORD }}"
