name: CD

on:
  push:
    tags:
      - "*"

jobs:
  deploy-pypi:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Set up Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Build wheel and deploy on PyPI
        run: |
          export TAG=${GITHUB_REF##*/}
          test $($HOME/.poetry/bin/poetry version | cut -f 2 -d " ") == $TAG
          echo Building for tag "$TAG"
          $HOME/.poetry/bin/poetry build
          $HOME/.poetry/bin/poetry publish -u "${{ secrets.PYPI_LOGIN }}" -p "${{ secrets.PYPI_PASSWORD }}"
